services:
  postgres:
    image: postgres:15
    container_name: little_limone_pgsql
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: little_limone_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - little-limone-net

volumes:
  pgdata:
   name: little_limone_pgdata

networks:
  little-limone-net:
    driver: bridge
